#!/bin/bash

# SPDX-FileCopyrightText: © 2026 Jeffrey C. Ollie
# SPDX-License-Identifier: MIT

cache="$BUILDKITE_PLUGIN_ATTIC_CACHE_CACHE"
if [[ "$cache" == "" ]]; then
  cache="$ATTIC_CACHE_CACHE"
fi
if [[ "$cache" == "" ]]; then
  echo "Missing cache configuration."
  exit 1
fi

# try and kill the "watch-store" background command
pid=$(cat "$ATTIC_TMP_DIR/watch-store.pid")
if [[ -n "$pid" ]]; then
  kill "$pid"
fi

echo "--- :notebook: 'attic watch-store' log"
if [[ -f "$ATTIC_TMP_DIR/watch-store.log" ]]; then
  cat "$ATTIC_TMP_DIR/watch-store.log"
fi

# list out everything that's in the store
nix path-info --all | LANG=C sort > "$ATTIC_TMP_DIR/after"

# compare that to what we started out
comm -13 "$ATTIC_TMP_DIR/before"  "$ATTIC_TMP_DIR/after" > "$ATTIC_TMP_DIR/new"

echo "--- :notebook: pushing new store entries to the cache"
# try and push all the new stuff to our cache
cat "$ATTIC_TMP_DIR/new" | nix run nixpkgs#attic-client -- push "$cache" --stdin
